server:
  port: 8081

spring:
  application:
    name: MOVIES-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/MoviesService
    username: postgres
    password: Mortynation@24
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


