server:
  port: 8081

spring:
  application:
    name: movies-service
  datasource:
    url: jdbc:postgresql://localhost:5432/MoviesService
    username: postgres
    password: Mortynation@24
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
