server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: REVIEWERS-SERVICE
          uri: lb://REVIEWERS-SERVICE
          predicates:
            - Path=/reviewers/**
        - id: MOVIES-SERVICE
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
